# Generated by Django 6.0.3 on 2026-03-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_description_en_product_description_my_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_my',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='year_en',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='year_my',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
