# Generated by Django 6.0.3 on 2026-03-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_price_alter_product_price_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='year_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='year_my',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
